#!/bin/bash
set -eo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_GREC_ROOT="$(cd -- "${SCRIPT_DIR}/../../.." && pwd)"
: "${GREC_ROOT:=$DEFAULT_GREC_ROOT}"

if [[ ! -d "$GREC_ROOT" ]]; then
  echo "Error: GREC_ROOT does not exist: $GREC_ROOT" >&2
  exit 1
fi

cd "$GREC_ROOT" || exit 1

# Single dataset: Instruments
: "${ROOT_DIR:=${GREC_ROOT}}"
: "${DATA_ROOT:=${ROOT_DIR}/data}"
: "${MODEL_NAME:=qwen3-embedding-4B}"
: "${USE_MULTI_DATASETS:=false}"
: "${DATASET:=Instruments}"

# Required: checkpoint generated by index training.
: "${CKPT_PATH:=}"
if [[ -z "$CKPT_PATH" ]]; then
  echo "Error: CKPT_PATH is empty."
  echo "Example: CKPT_PATH=${GREC_ROOT}/index_train_runs/Instruments/index/qwen3-embedding-4B/run_tag/run_time/best_collision_model.pth bash scripts/index/Instruments/generate.sh"
  exit 1
fi

export ROOT_DIR DATA_ROOT MODEL_NAME USE_MULTI_DATASETS DATASET CKPT_PATH

# Optional overrides (examples):
#   BATCH_SIZE=64 DEVICE=cuda:0 OUTPUT_SUFFIX=.index_custom.json
bash "$GREC_ROOT/scripts/index/base/generate.sh"
